# Generated by Django 3.1.4 on 2021-01-07 18:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('html_id', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCoverContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='project_photo_containers')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='files')),
                ('use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('fa_id', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitman.quote')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('position', models.CharField(blank=True, max_length=1000)),
                ('company', models.CharField(blank=True, max_length=1000)),
                ('one_line_description', models.CharField(blank=True, max_length=1000)),
                ('brief_description', models.CharField(blank=True, max_length=1000)),
                ('full_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='project_photos')),
                ('full_image', models.ImageField(upload_to='project_photos')),
                ('show', models.BooleanField(default=True)),
                ('rank', models.IntegerField()),
                ('cover_image_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitman.projectcovercontainertype')),
            ],
        ),
    ]
