# Generated by Django 3.1.4 on 2021-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
