# Generated by Django 3.1.4 on 2021-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0003_auto_20210108_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
