# Generated by Django 3.1.4 on 2021-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0004_navigationitem_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
