# Generated by Django 3.1.4 on 2021-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0007_auto_20210108_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
